name: lighthouse_core
description: The backend code of the Lighthouse tool, shared by both the mobile and desktop versions of Lighthouse.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:

  flutter:
    sdk: flutter
  http: ^0.13.5
  cloud_firestore: ^4.4.5
  firebase_core: ^2.8.0
  cloud_functions: ^4.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: false
  fonts:
  - family: Courier_Prime
    fonts:
      - asset: assets/fonts/Courier_Prime/CourierPrime-Regular.ttf
      - asset: assets/fonts/Courier_Prime/CourierPrime-Italic.ttf
      - asset: assets/fonts/Courier_Prime/CourierPrime-Bold.ttf
      - asset: assets/fonts/Courier_Prime/CourierPrime-BoldItalic.ttf